### ISSUE TITLE
Minor reconstruction bug - missing photons

### ISSUE THREAD

**Issue by alicerobson** [HEP-FCC/heppy#35]
The issue occurs when hcals are used to reconstruct a photon from the energy of an associated ecal. In the code below, the second call to reconstruct_cluster can never produce a new photon because the previous call to reconstruct_cluster  has already locked this hcal cluster, thus the second reconstruct_cluster just returns.

def reconstruct_hcal(self, block, hcalid):
…
 else: # approx means that hcal energy>track energies so we must have a neutral hadron
                    #excess-ecal_energy is approximately hcal energy  - track energies
                    parent_ids = [block.uniqueid, hcalid] 
                    self.reconstruct_cluster(hcal, 'hcal_in', parent_ids, 
                                             excess-ecal_energy)
                    if ecal_energy:
                        #make a photon from the remaining ecal energies
                        #again history is confusingbecause hcal is used to provide direction
                        #be better to make several smaller photons one per ecal?
                        parent_ids = [block.uniqueid] + [ecal.uniqueid for ecal in ecals]
                        **self.reconstruct_cluster(hcal, 'ecal_in', parent_ids, ecal_energy)**

def reconstruct_cluster(self, cluster, layer, parent_ids,
                            energy=None, vertex=None):
        '''construct a photon if it is an ecal
           construct a neutral hadron if it is an hcal
        '''
        if self.locked[cluster.uniqueid]:
            return 
...
        self.locked[cluster.uniqueid] = True #just OK but not nice if hcal used to make ecal.
        …

**Comment by cbernet** [comment]
Fixed by Alice
